apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "route53-dynamic-dns.fullname" . }}
  labels:
    {{- include "route53-dynamic-dns.labels" . | nindent 4 }}
data: {{ tpl (.Files.Glob "files/*").AsConfig . | nindent 2 }}
