apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "route53-dynamic-dns.fullname" . }}
  labels:
    {{- include "route53-dynamic-dns.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "route53-dynamic-dns.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "route53-dynamic-dns.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: 
            - /bin/bash
          args:
            - /files/run.sh
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "route53-dynamic-dns.fullname" . }}-creds
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "route53-dynamic-dns.fullname" . }}-creds
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_DEFAULT_REGION
              value: us-east-1
          volumeMounts:
            - name: files
              mountPath: "/files"
      volumes:
        - name: files
          configMap:
            name: {{ include "route53-dynamic-dns.fullname" . }}
